/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia_olimpo_p2_prc4.formularios;

import farmacia_olimpo_p2_prc4.clases.Empleado;
import farmacia_olimpo_p2_prc4.clases.Ventas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jarvi
 */
public class Historial extends javax.swing.JFrame {

    Ventas vent = new Ventas();
    DefaultTableModel modelo = new DefaultTableModel();

    public Historial() {

        initComponents();
        CargarDatosLocal();
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/ICONO FARMACIA EL OLIMPO.png"));

        return retValue;
    }

    public void CargarDatosLocal() {
        //Inicializamos 
        tblMantenimientoVentas.setModel(vent.CargarDatos());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar1 = new javax.swing.JPanel();
        Regresar1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMantenimientoVentas = new javax.swing.JTable();
        lblDerecho = new javax.swing.JLabel();
        lblHazVenta1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HIstorial de Ventas ");
        setLocation(new java.awt.Point(500, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar1.setBackground(new java.awt.Color(0, 102, 255));
        btnRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseClicked(evt);
            }
        });

        Regresar1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        Regresar1.setForeground(new java.awt.Color(255, 255, 255));
        Regresar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regresar1.setText("<   Regresar");
        Regresar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRegresar1Layout = new javax.swing.GroupLayout(btnRegresar1);
        btnRegresar1.setLayout(btnRegresar1Layout);
        btnRegresar1Layout.setHorizontalGroup(
            btnRegresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresar1Layout.createSequentialGroup()
                .addComponent(Regresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnRegresar1Layout.setVerticalGroup(
            btnRegresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegresar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Regresar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        tblMantenimientoVentas.setBackground(new java.awt.Color(255, 255, 255));
        tblMantenimientoVentas.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tblMantenimientoVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdVentas", "Cliente", "Vendedor", "Total", "Producto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMantenimientoVentas.setGridColor(new java.awt.Color(0, 0, 153));
        tblMantenimientoVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMantenimientoVentasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMantenimientoVentas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 1080, 570));
        jPanel1.add(lblDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 50, 780));

        lblHazVenta1.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        lblHazVenta1.setForeground(new java.awt.Color(0, 0, 153));
        lblHazVenta1.setText("Historial de Ventas");
        jPanel1.add(lblHazVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 620, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 1130, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar1MouseClicked
        frmConfiguracion newframe = new frmConfiguracion();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Regresar1MouseClicked

    private void btnRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseClicked
        frmInicio newframe = new frmInicio();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1MouseClicked

    private void tblMantenimientoVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMantenimientoVentasMouseClicked
        int i = tblMantenimientoVentas.getSelectedRow();
        TableModel model = tblMantenimientoVentas.getModel();
        //this.txtidDetalle.enable(false);
        //this.txtidDetalle.setText(model.getValueAt(i, 0).toString());
        //this.txtNombreProducto.setText(model.getValueAt(i, 1).toString());
        //this.txtPrecio.setText(model.getValueAt(i, 2).toString());
        // this.txtStock.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tblMantenimientoVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Regresar1;
    private javax.swing.JPanel btnRegresar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDerecho;
    private javax.swing.JLabel lblHazVenta1;
    private javax.swing.JTable tblMantenimientoVentas;
    // End of variables declaration//GEN-END:variables
}
